[package]
name = "neutron-dao-pre-propose-overrule"
version = "0.1.0"
authors = ["oldremez"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cwd-pre-propose-base = { version = "*", path = "../cwd-pre-propose-base" }
schemars = "0.8.8"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
