[package]
name = "cwd-subdao-proposal-single"
version = "0.2.0"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A Neutron subDAO proposal module for single choice (yes / no) voting."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
neutron_bindings = { package = "neutron-sdk", version = "0.1.0" }
cosmwasm-std = { version = "1.0.0", features = ["ibc3"] }
cosmwasm-storage = { version = "1.0.0" }
cw-storage-plus = "0.13"
cw-utils = "0.13"
cw2 = "0.13"
cw20 = "0.13"
cw3 = "0.13"
schemars = "0.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }

neutron-subdao-core = { path = "../../../../packages/neutron-subdao-core" }
cwd-macros = { path = "../../../../packages/cwd-macros" }
cwd-pre-propose-base = { path = "../../../../packages/cwd-pre-propose-base" }
cwd-subdao-pre-propose-single = { path = "../../pre-propose/cwd-subdao-pre-propose-single" }
cwd-interface = { path = "../../../../packages/cwd-interface" }
cwd-voting = { path = "../../../../packages/cwd-voting" }
cwd-hooks = { path = "../../../../packages/cwd-hooks" }
cwd-proposal-hooks = { path = "../../../../packages/cwd-proposal-hooks" }
cwd-vote-hooks = { path = "../../../../packages/cwd-vote-hooks" }
neutron-subdao-proposal-single = { path = "../../../../packages/neutron-subdao-proposal-single" }
neutron-subdao-pre-propose-single = { path = "../../../../packages/neutron-subdao-pre-propose-single" }
voting-v1 = { package = "voting", version = "0.1.0", git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v1.0.0" }
cw-proposal-single-v1 = { package = "cw-proposal-single", version = "0.1.0", git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v1.0.0" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
cw-multi-test = "0.13"
cw-denom = { path = "../../../../packages/cw-denom" }
cw20-base = "0.13"
cw721-base = "0.13"
cw4 = "0.13"
cw4-group = "0.13"

