[package]
authors = ["ekez ekez@withoutdoing.com"]
description = "A package macros for deriving DAO module interfaces."
edition = "2021"
name = "cwd-macros"
repository = "https://github.com/DA0-DA0/dao-contracts"
version = "0.2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["derive"]}

[dev-dependencies]
cosmwasm-schema = {version = "1.3.0"}
cosmwasm-std = {version = "1.3.0"}
cwd-interface = {path = "../cwd-interface"}
schemars = "0.8.8"
serde = {version = "1.0.175", default-features = false, features = ["derive"]}
