[package]
name = "neutron-subdao-pre-propose-single"
version = "0.1.0"
authors = ["Sergei Sotnikov <sergei.s@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cwd-pre-propose-base = { version = "*", path = "../cwd-pre-propose-base" }
schemars = "0.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
cosmwasm-std = "1.0.0"
neutron-sdk = "0.5.0"
cwd-voting = { path = "../cwd-voting" }
cwd-interface = { path = "../cwd-interface" }
